application:
  title: 'User Service'
  version: 0.0.1-snapshot
  author: 'Tino Acuna'

server:
  port: 9004

spring:
  application:
    name: user-service
  data:
    mongodb:
      database: tinoacuna_db
      uri: mongodb://tinoacuna:tinoacuna@localhost:27017
      authentication-database: admin

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

encrypt:
  key: mitocode